dependencies:
  - ipykernel
  - myst-nb
  - port-for =0.3.1
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autobuild
  # TODO: https://github.com/conda-forge/jupyter-cache-feedstock/pull/5
  - sqlalchemy <1.4
